baseURL = "/"
languageCode = "en-us"
title = "Adopting Erlang"
theme = "custom"

pygmentsCodeFences=true
disableKinds=["taxonomy"]

[params]
BookMenuBundle="/docs/menu"
# BookSection="chapters"
images = ["/img/cover.png"]

[markup.goldmark.renderer]
unsafe= true