baseURL = "/"
languageCode = "en-us"
title = "Adopting Erlang"
theme = "custom"

pygmentsCodeFences=true
disableKinds=["taxonomy"]

[params]
version = "2024-06-06"
BookMenuBundle="/docs/menu"
# BookSection="chapters"
images = ["/img/cover.png"]

BookRepo = 'https://github.com/adoptingerlang/adoptingerlang'
BookCommitPath = 'commit'

[markup.goldmark.renderer]
unsafe= true