version: 2.1
jobs:
  export:
    docker:
      - image: silex/emacs:26.2-alpine
    steps:
      - checkout
      - run: emacs -batch adoptingerlang.org -q -l export.el
      - persist_to_workspace:
          root: .
          paths:
            - adoptingerlang.tex
            - content
      - store_artifacts:
          path: ./adoptingerlang.tex
      - store_artifacts:
          path: ./content
  deploy:
    docker:
      - image: circleci/node
        entrypoint: /bin/sh
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - attach_workspace:
          at: .
      - run: |
          sudo apt-get install -f python-pygments

          mkdir -p bin
          curl -L https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.tar.gz -o bin/hugo.tar.gz
          tar -xvf bin/hugo.tar.gz -C ./bin
          bin/hugo --gc --minify

          sudo npm install netlify-cli -g --unsafe-perm
          netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID

  pdf:
    docker:
      - image: schickling/latex
        entrypoint: /bin/sh
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          pdflatex adoptingerlang.tex
          pdflatex adoptingerlang.tex

      - store_artifacts:
          path: ./adoptingerlang.pdf

workflows:
  version: 2.1
  hugo_export:
    jobs:
      - export
      - deploy:
          requires:
            - export
      - pdf:
          requires:
            - export
