version: 2.1
jobs:
  export:
    docker:
      - image: silex/emacs:26.2-alpine
    steps:
      - restore_cache:
          keys:
            - emacs-packages-v1
      - checkout
      - run: emacs -batch adoptingerlang.org -q -l export.el

      - save_cache:
          key: emacs-packages-v1
          paths:
            - /root/.emacs.d

      - persist_to_workspace:
          root: .
          paths:
            - adoptingerlang.tex
            - content
      - store_artifacts:
          path: ./adoptingerlang.tex
      - store_artifacts:
          path: ./content

  deploy:
    parameters:
      deploy_args:
        type: string
        default: ""
    docker:
      - image: tristan/hugo_netlify:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          /opt/hugo --gc --minify
          netlify deploy << parameters.deploy_args >> --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID

  pdf:
    docker:
      - image: aergus/latex
        entrypoint: /bin/sh
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          pdflatex -shell-escape adoptingerlang.tex
          pdflatex -shell-escape adoptingerlang.tex

      - store_artifacts:
          path: ./adoptingerlang.pdf

workflows:
  version: 2.1
  hugo_export:
    jobs:
      - export

      - deploy:
          name: "preview"
          requires:
            - export

      - deploy:
          name: "prod"
          deploy_args: "--prod"
          requires:
            - export
          filters:
            branches:
              only:
                - master

      - pdf:
          requires:
            - export
