version: 2.1
jobs:
  export:
    docker:
      - image: silex/emacs:27.2-ci
    steps:
      - restore_cache:
          keys:
            - emacs-packages-v2
      - checkout
      - run: |
          emacs -batch adoptingerlang.org -q -l export.el

      - save_cache:
          key: emacs-packages-v2
          paths:
            - /root/.emacs.d

      - persist_to_workspace:
          root: .
          paths:
            - ./*

  deploy:
    parameters:
      deploy_args:
        type: string
        default: ""
    docker:
      - image: tristan/hugo_netlify:hugo-0.58.3
    steps:
      # - checkout
      - attach_workspace:
          at: .
      - run: |
          /opt/hugo --gc --minify
          netlify deploy << parameters.deploy_args >> --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID

  # pdf:
  #   docker:
  #     - image: aergus/latex
  #       entrypoint: /bin/sh
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: .
  #     - run: |
  #         pdflatex -shell-escape adoptingerlang.tex
  #         pdflatex -shell-escape adoptingerlang.tex

  #     - store_artifacts:
  #         path: ./adoptingerlang.pdf

workflows:
  version: 2.1
  hugo_export:
    jobs:
      - export

      - deploy:
          name: "preview"
          requires:
            - export

      - deploy:
          name: "prod"
          deploy_args: "--prod"
          requires:
            - export
          filters:
            branches:
              only:
                - master

      # - pdf:
      #     requires:
      #       - export
