version: 2.1
jobs:
  export:
    docker:
      - image: silex/emacs:26.2-alpine
    steps:
      - checkout
      - run: emacs -batch adoptingerlang.org -q -l export.el
workflows:
  version: 2.1
  hugo_export:
    jobs:
      - export:
          filters:
            branches:
              only: master
