name: CI

on:
  push:
    branches:
      - main
    tags:
      - "snapshot-*"
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 29.1

      - name: Run Emacs Script
        run: emacs -batch adoptingerlang.org -q -l export.el

      - name: Setup Hugo
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.127.0'
          extended: true

      - name: Hugo Build
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: hugo --gc --minify

      - name: Deploy to Netlify
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './public'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          # enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Push snapshot branch
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          export DEPLOY_BRANCH_NAME=${GITHUB_REF_NAME#snapshot-}
          git config --global user.name 'Tristan Sloughter'
          git config --global user.email 'tsloughter@users.noreply.github.com'
          git checkout -b ${DEPLOY_BRANCH_NAME}
          git add --force --all content/
          git commit -m "action: add built site in public/ to deploy to netlify in branch deploy"
          git push origin ${DEPLOY_BRANCH_NAME}:${DEPLOY_BRANCH_NAME}
